---
# defaults file for ansible-telegraf

telegraf_agent_version: 1.5.1
telegraf_agent_hostname: "{{ ansible_fqdn }}"
telegraf_agent_interval: 10
telegraf_agent_debug: False
telegraf_agent_round_interval: True
telegraf_agent_flush_interval: 10
telegraf_agent_flush_jitter: 0
telegraf_agent_aws_tags: False
telegraf_agent_aws_tags_prefix: ""

# v0.13 settings (not sure if supported in older version):
telegraf_agent_collection_jitter: 0
telegraf_agent_metric_batch_size: 1000
telegraf_agent_metric_buffer_limit: 10000
telegraf_agent_quiet: False

# v1.1 settings:
telegraf_agent_logfile: ""
telegraf_agent_omit_hostname: False

telegraf_global_tags: []

telegraf_agent_output:
  # - type: influxdb
  #   config:
  #     - urls = ["http://localhost:8086"]
  #     - database = "telegraf"
  #     - precision = "s"

  - type: prometheus_client
    config:
      - listen = ":9273"
      - path = "/metrics"   
      - expiration_interval = "60s"

telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: io
  - plugin: mem
  - plugin: net
  - plugin: system
  - plugin: swap
  - plugin: netstat
  - plugin: redis
    config:
      - servers = ["tcp://:{{redis_pass}}@localhost:7000", "tcp://:{{redis_pass}}@localhost:7001"]


telegraf_plugins_extra:

