---

- set_fact:
    setup_script_checksum: "md5:{{ setup_script_md5_sum }}"
  when: setup_script_md5_sum is defined and setup_script_md5_sum

- name: Download docker setup script for desired version
  get_url:
    url: "{{ setup_script_url }}"
    dest: "/tmp/docker-setup.sh"
    checksum: "{{ setup_script_checksum|default(omit) }}"
    mode: 0755

- name: Execute docker setup script
  # command wrapped in PATH reset to ensure ansible-container compatibility
  shell: "env -i PATH=$PATH bash -c '/tmp/docker-setup.sh'"